module.exports = {
  content: ['./index.html', './privacidad/**/*.html', './terminos/**/*.html', './src/**/*.{html,js}'],
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
      darkMode: "class",
      theme: {
        extend: {
          colors: {
            "on-surface-variant": "#c3c6d7",
            "surface": "#0b1326",
            "inverse-surface": "#dae2fd",
            "on-primary-container": "#eeefff",
            "surface-tint": "#b4c5ff",
            "on-error-container": "#ffdad6",
            "surface-container": "#171f33",
            "tertiary-container": "#606e84",
            "inverse-on-surface": "#283044",
            "tertiary": "#b9c7e0",
            "error-container": "#93000a",
            "on-primary-fixed": "#00174b",
            "error": "#ffb4ab",
            "tertiary-fixed-dim": "#b9c7e0",
            "secondary-fixed": "#d8e2ff",
            "secondary-container": "#0566d9",
            "background": "#0b1326",
            "primary-fixed-dim": "#b4c5ff",
            "outline-variant": "#434655",
            "on-secondary-fixed-variant": "#004395",
            "on-error": "#690005",
            "on-primary-fixed-variant": "#003ea8",
            "on-tertiary-fixed-variant": "#3a485c",
            "secondary": "#adc6ff",
            "secondary-fixed-dim": "#adc6ff",
            "on-secondary-fixed": "#001a42",
            "primary-container": "#2563eb",
            "outline": "#8d90a0",
            "on-tertiary": "#233144",
            "on-primary": "#002a78",
            "primary": "#b4c5ff",
            "surface-container-highest": "#2d3449",
            "surface-container-lowest": "#060e20",
            "on-surface": "#dae2fd",
            "surface-container-high": "#222a3d",
            "surface-variant": "#2d3449",
            "on-background": "#dae2fd",
            "surface-container-low": "#131b2e",
            "tertiary-fixed": "#d5e3fd",
            "on-secondary": "#002e6a",
            "surface-dim": "#0b1326",
            "inverse-primary": "#0053db",
            "primary-fixed": "#dbe1ff",
            "surface-bright": "#31394d",
            "on-secondary-container": "#e6ecff",
            "on-tertiary-fixed": "#0d1c2f",
            "on-tertiary-container": "#eaf0ff"
          },
          borderRadius: {
            DEFAULT: "0.125rem",
            lg: "0.25rem",
            xl: "0.5rem",
            full: "0.75rem"
          },
          spacing: {
            "space-xl": "2.5rem",
            "space-md": "1rem",
            "margin-mobile": "1.25rem",
            "space-lg": "1.5rem",
            "margin": "3rem",
            "space-sm": "0.5rem",
            "gutter": "1.5rem",
            "space-xs": "0.25rem",
            "gutter-mobile": "1rem"
          },
          fontFamily: {
            "headline-lg": ["Geist", "sans-serif"],
            "body-lg": ["Geist", "sans-serif"],
            "headline-sm": ["Geist", "sans-serif"],
            "body-sm": ["Geist", "sans-serif"],
            "display-hero-mobile": ["Geist", "sans-serif"],
            "label-caption": ["Geist", "sans-serif"],
            "headline-md": ["Geist", "sans-serif"],
            "display-hero": ["Geist", "sans-serif"],
            "body-md": ["Geist", "sans-serif"],
            "label-code": ["JetBrains Mono", "monospace"],
            "headline-lg-mobile": ["Geist", "sans-serif"]
          },
          fontSize: {
            "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.025em", fontWeight: "600" }],
            "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "400" }],
            "headline-sm": ["20px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "600" }],
            "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
            "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "700" }],
            "label-caption": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
            "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.015em", fontWeight: "600" }],
            "display-hero": ["64px", { lineHeight: "72px", letterSpacing: "-0.03em", fontWeight: "700" }],
            "body-md": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
            "label-code": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
            "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }]
          }
        }
      }
    }

